import type { Business, FundingOpportunity, BusinessOpportunityRecord } from '../types/business';
import type { Article, Comment } from '../types/article';

const TODAY = new Date();
const SUB_DAYS = (days: number) => {
  const d = new Date(TODAY);
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const MOCK_BUSINESSES: Business[] = [
  {
    id: 'b1',
    slug: 'nha-hang-an-nam',
    name: 'An Nam Culinary',
    legalName: 'Công ty TNHH Ẩm Thực An Nam',
    description: 'Chuỗi nhà hàng ẩm thực truyền thống Việt Nam kết hợp phong cách hiện đại.',
    detailedOverview: 'An Nam Culinary được thành lập năm 2018 với mục tiêu nâng tầm và giữ gìn văn hóa ẩm thực Việt Nam thông qua chuỗi nhà hàng sang trọng. Hiện chuỗi vận hành 4 chi nhánh tại TP.HCM và phục vụ hơn 15,000 lượt khách mỗi tháng.',
    industry: 'Food & Beverage',
    businessType: 'Small Business',
    businessStage: 'Operating',
    foundedYear: 2018,
    yearsInOperation: 6,
    employeeRange: '50-100 nhân viên',
    location: 'Ho Chi Minh City, VN',
    operatingRegions: ['TP.HCM', 'Đồng Nai'],
    mainMarket: 'Khách hàng cá nhân, gia đình và sự kiện doanh nghiệp',
    businessModel: 'B2C & B2B Catering',
    verified: true,
    website: 'https://annamculinary.vn',
    productsOrServices: 'Ẩm thực Việt Nam, catering event, gói quà tặng ẩm thực cao cấp',
    createdAt: SUB_DAYS(100),
    savedCount: 142,
    commentCount: 18,
    viewCount: 1200,
    teamMembers: [
      { id: 't1', name: 'Nguyễn Văn An', role: 'Founder & CEO', bio: 'Hơn 12 năm kinh nghiệm trong ngành F&B và điều hành chuỗi nhà hàng cao cấp.' },
      { id: 't2', name: 'Trần Thị Mai', role: 'Head Chef', bio: 'Bếp trưởng với 15 năm sáng tạo và bảo tồn các món ăn truyền thống.' }
    ],
    financialHighlights: {
      revenueRange: '10 – 20 tỷ VNĐ / năm',
      growthRange: '15% – 25% / năm',
      profitabilityStatus: 'Đã có lợi nhuận',
      reportingPeriod: 'Năm 2023',
      currency: 'VND',
      selfReported: true,
    },
    fundingRounds: [
      {
        id: 'fr1',
        roundName: 'Seed',
        amount: 5000000000,
        currency: 'VND',
        date: '2020-05-10T00:00:00.000Z',
        investors: 'Angel Investors',
        isVerified: true
      }
    ]
  },
  {
    id: 'b2',
    slug: 'greenflow-tech',
    name: 'GreenFlow',
    legalName: 'Công ty Cổ phần Công nghệ GreenFlow',
    description: 'Smart energy management solution for commercial buildings optimizing power consumption.',
    detailedOverview: 'GreenFlow phát triển hệ sinh thái cảm biến IoT kết hợp thuật toán AI để giám sát, phân tích và tối ưu hóa việc tiêu thụ điện năng tại các tòa nhà văn phòng và trung tâm thương mại, giúp giảm đến 30% chi phí điện năng.',
    industry: 'Technology',
    businessType: 'Startup',
    businessStage: 'Early Stage',
    foundedYear: 2023,
    yearsInOperation: 1,
    employeeRange: '10-20 nhân viên',
    location: 'Hanoi, VN',
    operatingRegions: ['Hà Nội', 'Đà Nẵng'],
    mainMarket: 'Chủ đầu tư bất động sản thương mại và quản lý tòa nhà',
    businessModel: 'SaaS & IoT Hardware Leasing',
    verified: true,
    website: 'https://greenflowtech.io',
    productsOrServices: 'IoT Energy Sensors, AI Analytics SaaS Platform',
    createdAt: SUB_DAYS(5),
    savedCount: 210,
    commentCount: 35,
    viewCount: 2500,
    teamMembers: [
      { id: 't3', name: 'Lê Hoàng Nam', role: 'Co-Founder & CTO', bio: 'Kỹ sư IoT tốt nghiệp Bách Khoa, 8 năm kinh nghiệm tại các tập đoàn công nghệ.' }
    ],
    financialHighlights: {
      revenueRange: '1 – 3 tỷ VNĐ / năm',
      growthRange: '100% / năm',
      profitabilityStatus: 'Đang đầu tư tái tăng trưởng',
      reportingPeriod: 'Quý 1/2024',
      currency: 'VND',
      selfReported: true,
    },
    fundingRounds: [
      {
        id: 'fr2',
        roundName: 'Pre-Seed',
        amount: 50000,
        currency: 'USD',
        date: '2023-11-20T00:00:00.000Z',
        investors: 'TechStars',
        isVerified: true
      },
      {
        id: 'fr3',
        roundName: 'Seed',
        amount: 250000,
        currency: 'USD',
        date: '2024-05-15T00:00:00.000Z',
        investors: 'Ventures XYZ',
        isVerified: false
      }
    ]
  },
  {
    id: 'b3',
    slug: 'may-mac-minh-thanh',
    name: 'Minh Thanh Garments',
    legalName: 'Công ty TNHH May Mặc Minh Thanh',
    description: 'Doanh nghiệp gia đình chuyên sản xuất và xuất khẩu hàng may mặc chất lượng cao.',
    detailedOverview: 'Minh Thanh Garments sở hữu xưởng sản xuất 3,000m2 tại Bình Dương với dây chuyền hiện đại, đáp ứng các đơn hàng xuất khẩu đi thị trường Châu Âu và Nhật Bản.',
    industry: 'Manufacturing',
    businessType: 'Family Business',
    businessStage: 'Growing',
    foundedYear: 2012,
    yearsInOperation: 12,
    employeeRange: '100-200 nhân viên',
    location: 'Binh Duong, VN',
    operatingRegions: ['Bình Dương', 'Xuất khẩu EU & Nhật Bản'],
    mainMarket: 'Các thương hiệu thời trang quốc tế và đồng phục doanh nghiệp lớn',
    businessModel: 'OEM / ODM Manufacturing',
    verified: true,
    productsOrServices: 'Quần áo thời trang, đồng phục công sở, trang phục bảo hộ',
    createdAt: SUB_DAYS(40),
    savedCount: 95,
    commentCount: 12,
    viewCount: 890,
    financialHighlights: {
      revenueRange: '50 – 100 tỷ VNĐ / năm',
      growthRange: '10% – 15% / năm',
      profitabilityStatus: 'Có lợi nhuận ổn định',
      reportingPeriod: 'Năm 2023',
      currency: 'VND',
      selfReported: true,
    }
  },
  {
    id: 'b4',
    slug: 'nong-san-xanh-dalat',
    name: 'Da Lat Green Organic',
    description: 'Hợp tác sản xuất và phân phối nông sản hữu cơ sạch đạt chuẩn GlobalGAP.',
    industry: 'Agriculture',
    businessType: 'Cooperative',
    businessStage: 'Expansion',
    foundedYear: 2019,
    yearsInOperation: 5,
    location: 'Lam Dong, VN',
    verified: false,
    productsOrServices: 'Rau củ hữu cơ, trái cây sấy dẻo',
    createdAt: SUB_DAYS(15),
    savedCount: 180,
    commentCount: 22,
    viewCount: 1650,
  },
  {
    id: 'b5',
    slug: 'chuoi-cafe-viet',
    name: 'Viet Coffee House Franchise',
    description: 'Nhượng quyền thương hiệu cà phê rang xay nguyên chất với hơn 30 điểm bán.',
    industry: 'Hospitality',
    businessType: 'Franchise',
    businessStage: 'Mature',
    foundedYear: 2016,
    yearsInOperation: 8,
    location: 'Da Nang, VN',
    verified: true,
    productsOrServices: 'Cà phê hạt, gói nhượng quyền kinh doanh',
    createdAt: SUB_DAYS(60),
    savedCount: 310,
    commentCount: 45,
    viewCount: 3400,
  },
  {
    id: 'b6',
    slug: 'eco-crafts-vietnam',
    name: 'EcoCrafts Social Enterprise',
    description: 'Doanh nghiệp xã hội tạo việc làm cho người yếu thế qua quà tặng thủ công mỹ nghệ.',
    industry: 'Retail',
    businessType: 'Social Enterprise',
    businessStage: 'Operating',
    foundedYear: 2021,
    yearsInOperation: 3,
    location: 'Hue, VN',
    verified: true,
    productsOrServices: 'Túi mây tre đan, sản phẩm tái chế',
    createdAt: SUB_DAYS(2),
    savedCount: 78,
    commentCount: 9,
    viewCount: 620,
  },
  {
    id: 'b7',
    slug: 'smart-logistics-express',
    name: 'SmartLog Express',
    description: 'Giải pháp giao vận kho vận chặng cuối ứng dụng thuật toán tối ưu tuyến đường.',
    industry: 'Logistics',
    businessType: 'Online Business',
    businessStage: 'Growing',
    foundedYear: 2022,
    yearsInOperation: 2,
    location: 'Ho Chi Minh City, VN',
    verified: true,
    productsOrServices: 'Dịch vụ kho bãi, giao hàng nội thành',
    createdAt: SUB_DAYS(20),
    savedCount: 155,
    commentCount: 19,
    viewCount: 1400,
  },
  {
    id: 'b8',
    slug: 'medix-ai-health',
    name: 'Medix AI',
    description: 'AI-powered diagnostics platform for faster and accurate care in remote areas.',
    industry: 'Healthcare',
    businessType: 'Startup',
    businessStage: 'Early Stage',
    foundedYear: 2023,
    yearsInOperation: 1,
    location: 'Singapore',
    verified: true,
    productsOrServices: 'Medical Imaging AI Scanner',
    createdAt: SUB_DAYS(8),
    savedCount: 280,
    commentCount: 52,
    viewCount: 2900,
  },
  {
    id: 'b9',
    slug: 'edu-smart-academy',
    name: 'EduSmart Academy',
    description: 'Trung tâm đào tạo kỹ năng số và lập trình cho học sinh tiểu học và trung học.',
    industry: 'Education',
    businessType: 'Small Business',
    businessStage: 'Expansion',
    foundedYear: 2020,
    yearsInOperation: 4,
    location: 'Can Tho, VN',
    verified: false,
    productsOrServices: 'Khóa học STEM, chứng chỉ kỹ năng số',
    createdAt: SUB_DAYS(30),
    savedCount: 112,
    commentCount: 14,
    viewCount: 980,
  },
  {
    id: 'b10',
    slug: 'luat-cong-chung-saigon',
    name: 'Saigon Legal Consult',
    description: 'Công ty tư vấn pháp lý doanh nghiệp, M&A và sở hữu trí tuệ uy tín.',
    industry: 'Professional Services',
    businessType: 'Small Business',
    businessStage: 'Mature',
    foundedYear: 2015,
    yearsInOperation: 9,
    location: 'Ho Chi Minh City, VN',
    verified: true,
    productsOrServices: 'Tư vấn pháp lý, thẩm định doanh nghiệp',
    createdAt: SUB_DAYS(120),
    savedCount: 88,
    commentCount: 7,
    viewCount: 750,
  },
  {
    id: 'b11',
    slug: 'shopzy-ecommerce',
    name: 'Shopzy',
    description: 'Nền tảng thương mại điện tử mua sắm thông minh tích hợp giỏ hàng hợp nhất.',
    industry: 'Retail',
    businessType: 'Online Business',
    businessStage: 'Growing',
    foundedYear: 2022,
    yearsInOperation: 2,
    location: 'Hanoi, VN',
    verified: true,
    productsOrServices: 'E-commerce SaaS Platform',
    createdAt: SUB_DAYS(1),
    savedCount: 165,
    commentCount: 27,
    viewCount: 1850,
  },
  {
    id: 'b12',
    slug: 'mobi-pay-fintech',
    name: 'MobiPay Fintech',
    description: 'Giải pháp thanh toán QR mã nguồn mở cho các cửa hàng bán lẻ truyền thống.',
    industry: 'Technology',
    businessType: 'Startup',
    businessStage: 'Idea',
    foundedYear: 2024,
    yearsInOperation: 0,
    location: 'Da Nang, VN',
    verified: false,
    productsOrServices: 'Cổng thanh toán QR, phần mềm Pos',
    createdAt: SUB_DAYS(0),
    savedCount: 45,
    commentCount: 8,
    viewCount: 420,
  }
];

export const MOCK_FUNDING_OPPORTUNITIES: FundingOpportunity[] = [
  {
    id: 'fo1',
    slug: 'nha-hang-an-nam-expansion',
    businessId: 'b1',
    businessName: 'An Nam Culinary',
    title: 'Mở rộng 3 chi nhánh nhà hàng tại Quận 1 & Thủ Đức',
    shortDescription: 'Cần vốn lưu động và chi phí mặt bằng để phát triển chuỗi ẩm thực.',
    detailedOverview: 'An Nam Culinary đang tìm kiếm đối tác đầu tư cổ phần để tài trợ cho việc khai trương 3 chi nhánh cao cấp mới tại TP.HCM trong Quý 4/2024.',
    fundingAmountMin: 2000000000,
    fundingAmountMax: 3500000000,
    currency: 'VND',
    fundingPurpose: 'Open New Location',
    fundingType: 'Equity Investment',
    status: 'Published',
    publishedAt: SUB_DAYS(10),
    deadline: SUB_DAYS(-60),
    timelineDescription: 'Dự kiến giải ngân trong vòng 60 ngày kể từ khi ký kết.',
    useOfFunds: [
      { category: 'Thuê & Đặt cọc mặt bằng', percentage: 40, description: 'Chi phí đặt cọc 6 tháng cho 3 vị trí đắc địa' },
      { category: 'Thiết kế & Trang trí nội thất', percentage: 35, description: 'Thi công theo diện mạo sang trọng truyền thống' },
      { category: 'Vốn lưu động & Marketing', percentage: 25, description: 'Tuyển dụng nhân sự và chiến dịch khai trương' }
    ],
    growthPlan: {
      context: 'Nhu cầu ẩm thực trải nghiệm tăng mạnh tại các vùng trung tâm đô thị.',
      opportunity: 'Mở rộng quy mô giúp tối ưu hóa chi phí nguyên liệu đầu vào đến 15%.',
      plannedActivities: 'Khai trương dần từng chi nhánh trong 6 tháng tới.',
      timeline: 'Tháng 9/2024 - Tháng 3/2025',
      mainRisks: 'Biến động giá thuê mặt bằng và chi phí nhân sự F&B.'
    },
    publicDocuments: [
      { id: 'd1', title: 'Executive Summary - An Nam Culinary 2024', type: 'PDF Pitch Deck', fileSize: '2.4 MB' }
    ]
  },
  {
    id: 'fo2',
    slug: 'greenflow-seed-round',
    businessId: 'b2',
    businessName: 'GreenFlow',
    title: 'Gọi vốn vòng Seed hoàn thiện dòng sản phẩm cảm biến IoT',
    shortDescription: 'Tăng tốc phát triển phần mềm AI và mở rộng đội ngũ kinh doanh.',
    detailedOverview: 'GreenFlow mở vòng gọi vốn Seed nhằm nâng cấp thế hệ cảm biến IoT 2.0 và ký kết hợp đồng thử nghiệm với 10 tòa nhà hạng A tại Hà Nội.',
    fundingAmountMin: 1200000000,
    fundingAmountMax: 2500000000,
    currency: 'VND',
    fundingPurpose: 'Product Development',
    fundingType: 'Convertible Investment',
    status: 'Published',
    publishedAt: SUB_DAYS(5),
    useOfFunds: [
      { category: 'R&D & Sản xuất mẫu phần cứng', percentage: 50, description: 'Sản xuất 1,000 cảm biến IoT thế hệ mới' },
      { category: 'Tuyển dụng Kỹ sư AI', percentage: 30, description: 'Nâng cấp thuật toán dự báo điện năng' },
      { category: 'Chi phí vận hành', percentage: 20, description: 'Vận hành văn phòng và hạ tầng cloud' }
    ]
  },
  {
    id: 'fo3',
    slug: 'minh-thanh-equipment-loan',
    businessId: 'b3',
    businessName: 'Minh Thanh Garments',
    title: 'Đầu tư dàn máy may tự động công nghệ Nhật Bản',
    shortDescription: 'Nâng cao năng suất sản xuất cho các đơn hàng xuất khẩu đi Châu Âu.',
    detailedOverview: 'Vay vốn doanh nghiệp ngắn hạn để mua sắm hệ thống dây chuyền tự động hóa giúp tăng năng suất 40%.',
    fundingAmountMin: 600000000,
    fundingAmountMax: 1000000000,
    currency: 'VND',
    fundingPurpose: 'Purchase Equipment',
    fundingType: 'Business Loan',
    status: 'Published',
    publishedAt: SUB_DAYS(40),
  },
  {
    id: 'fo4',
    slug: 'dalat-green-working-capital',
    businessId: 'b4',
    businessName: 'Da Lat Green Organic',
    title: 'Bổ sung vốn lưu động mùa thu hoạch nông sản sạch',
    shortDescription: 'Thu mua nông sản trực tiếp từ 50 hộ nông dân hợp tác xã.',
    fundingAmountMin: 300000000,
    fundingAmountMax: 500000000,
    currency: 'VND',
    fundingPurpose: 'Working Capital',
    fundingType: 'Revenue Sharing',
    status: 'Published',
    publishedAt: SUB_DAYS(15),
  },
  {
    id: 'fo5',
    slug: 'viet-coffee-franchise-expansion',
    businessId: 'b5',
    businessName: 'Viet Coffee House Franchise',
    title: 'Tìm đối tác nhượng quyền & đầu tư chiến lược mở rộng miền Bắc',
    shortDescription: 'Hợp tác phát triển mạng lưới nhượng quyền thương hiệu tại Hà Nội.',
    fundingAmountMin: 5000000000,
    fundingAmountMax: 10000000000,
    currency: 'VND',
    fundingPurpose: 'Business Expansion',
    fundingType: 'Strategic Partnership',
    status: 'Published',
    publishedAt: SUB_DAYS(60),
  },
  {
    id: 'fo6',
    slug: 'ecocrafts-digital-transformation',
    businessId: 'b6',
    businessName: 'EcoCrafts Social Enterprise',
    title: 'Chuyển đổi số và xây dựng trang thương mại điện tử xuất khẩu',
    shortDescription: 'Ứng dụng công nghệ để tiếp cận khách hàng quốc tế quan tâm đến ESG.',
    fundingAmountMin: 200000000,
    fundingAmountMax: 400000000,
    currency: 'VND',
    fundingPurpose: 'Digital Transformation',
    fundingType: 'Joint Venture',
    status: 'Published',
    publishedAt: SUB_DAYS(2),
  },
  {
    id: 'fo7',
    slug: 'smartlog-fleet-expansion',
    businessId: 'b7',
    businessName: 'SmartLog Express',
    title: 'Tăng cường đội xe tải van điện giao vận chặng cuối',
    shortDescription: 'Đầu tư phương tiện xanh giảm thiểu chi phí nhiên liệu.',
    fundingAmountMin: 1500000000,
    fundingAmountMax: 3000000000,
    currency: 'VND',
    fundingPurpose: 'Purchase Equipment',
    fundingType: 'Asset Financing',
    status: 'Published',
    publishedAt: SUB_DAYS(20),
  },
  {
    id: 'fo8',
    slug: 'medix-ai-series-a',
    businessId: 'b8',
    businessName: 'Medix AI',
    title: 'Series A funding for international clinical trial expansion',
    shortDescription: 'Expanding FDA approvals and entering SE Asia healthcare markets.',
    fundingAmountMin: 500000,
    fundingAmountMax: 1500000,
    currency: 'USD',
    fundingPurpose: 'Export Expansion',
    fundingType: 'Equity Investment',
    status: 'Published',
    publishedAt: SUB_DAYS(8),
  },
  {
    id: 'fo9',
    slug: 'edusmart-cantho-facility',
    businessId: 'b9',
    businessName: 'EduSmart Academy',
    title: 'Xây dựng phòng lab Robot & STEM công nghệ cao',
    shortDescription: 'Trang bị máy tính và thiết bị đào tạo tiên tiến cho học sinh.',
    fundingAmountMin: 400000000,
    fundingAmountMax: 800000000,
    currency: 'VND',
    fundingPurpose: 'Purchase Equipment',
    fundingType: 'Business Loan',
    status: 'Published',
    publishedAt: SUB_DAYS(30),
  },
  {
    id: 'fo10',
    slug: 'saigon-legal-marketing',
    businessId: 'b10',
    businessName: 'Saigon Legal Consult',
    title: 'Mở rộng kênh tiếp thị số & dịch vụ pháp lý doanh nghiệp',
    shortDescription: 'Xây dựng cổng tra cứu hợp đồng tự động cho SME.',
    fundingAmountMin: 300000000,
    fundingAmountMax: 600000000,
    currency: 'VND',
    fundingPurpose: 'Marketing',
    fundingType: 'Revenue Sharing',
    status: 'Published',
    publishedAt: SUB_DAYS(120),
  },
  {
    id: 'fo11',
    slug: 'shopzy-marketing-campaign',
    businessId: 'b11',
    businessName: 'Shopzy',
    title: 'Gọi vốn Marketing tăng trưởng người dùng quý 3',
    shortDescription: 'Đẩy mạnh chiến dịch quảng bá tới 10,000 cửa hàng bán lẻ nhỏ.',
    fundingAmountMin: 800000000,
    fundingAmountMax: 1500000000,
    currency: 'VND',
    fundingPurpose: 'Marketing',
    fundingType: 'Equity Investment',
    status: 'Published',
    publishedAt: SUB_DAYS(1),
  },
  {
    id: 'fo12',
    slug: 'mobipay-seed-capital',
    businessId: 'b12',
    businessName: 'MobiPay Fintech',
    title: 'Gọi vốn vòng khởi tạo triển khai thử nghiệm tại Da Nang',
    shortDescription: 'Phát triển bản MVP cổng thanh toán mã QR.',
    fundingAmountMin: 500000000,
    fundingAmountMax: 1000000000,
    currency: 'VND',
    fundingPurpose: 'Start Operations',
    fundingType: 'Equity Investment',
    status: 'Published',
    publishedAt: SUB_DAYS(0),
  },
  // Additional non-published status records for testing Section 25 status rules
  {
    id: 'fo13',
    slug: 'an-nam-closed-deal',
    businessId: 'b1',
    businessName: 'An Nam Culinary',
    title: 'Dự án đầu tư trung tâm chế biến nguyên liệu (Đã đóng)',
    shortDescription: 'Dự án gọi vốn lưu động năm 2022 đã kết thúc đàm phán thành công.',
    fundingAmountMin: 1000000000,
    fundingAmountMax: 1500000000,
    currency: 'VND',
    fundingPurpose: 'Working Capital',
    fundingType: 'Business Loan',
    status: 'Closed',
    publishedAt: SUB_DAYS(300),
  },
  {
    id: 'fo14',
    slug: 'greenflow-funded-round',
    businessId: 'b2',
    businessName: 'GreenFlow',
    title: 'Vòng gọi vốn Pre-Seed tài trợ nghiên cứu (Đã huy động xong)',
    shortDescription: 'Đã hoàn tất gọi vốn 500 triệu VNĐ từ quỹ thiên thần.',
    fundingAmountMin: 500000000,
    fundingAmountMax: 500000000,
    currency: 'VND',
    fundingPurpose: 'Start Operations',
    fundingType: 'Equity Investment',
    status: 'Funded',
    publishedAt: SUB_DAYS(200),
  },
  {
    id: 'fo15',
    slug: 'may-mac-archived',
    businessId: 'b3',
    businessName: 'Minh Thanh Garments',
    title: 'Chương trình phát triển dây chuyền 2021 (Lưu trữ)',
    shortDescription: 'Cơ hội kêu gọi hợp tác đã hoàn tất lưu trữ.',
    fundingAmountMin: 400000000,
    fundingAmountMax: 800000000,
    currency: 'VND',
    fundingPurpose: 'Purchase Equipment',
    fundingType: 'Asset Financing',
    status: 'Archived',
    publishedAt: SUB_DAYS(500),
  },
  {
    id: 'fo16',
    slug: 'draft-opportunity-private',
    businessId: 'b1',
    businessName: 'An Nam Culinary',
    title: 'Bản nháp cơ hội đầu tư chi nhánh 5 (Chưa công bố)',
    shortDescription: 'Nội dung đang soạn thảo.',
    fundingAmountMin: 500000000,
    fundingAmountMax: 1000000000,
    currency: 'VND',
    fundingPurpose: 'Business Expansion',
    fundingType: 'Equity Investment',
    status: 'Draft',
    publishedAt: SUB_DAYS(1),
  },
  {
    id: 'fo17',
    slug: 'rejected-opportunity-private',
    businessId: 'b2',
    businessName: 'GreenFlow',
    title: 'Dự án từ chối do thiếu hồ sơ',
    shortDescription: 'Không đủ điều kiện hiển thị.',
    fundingAmountMin: 100000000,
    fundingAmountMax: 200000000,
    currency: 'VND',
    fundingPurpose: 'Marketing',
    fundingType: 'Business Loan',
    status: 'Rejected',
    publishedAt: SUB_DAYS(2),
  }
];

export const MOCK_RECORDS: BusinessOpportunityRecord[] = MOCK_BUSINESSES.map(b => {
  const opp = MOCK_FUNDING_OPPORTUNITIES.find(f => f.businessId === b.id && f.status === 'Published');
  return {
    business: b,
    opportunity: opp,
  };
});


export const MOCK_ARTICLES: Article[] = [
  {
    id: 'a1',
    slug: '5-sai-lam-khi-goi-von-seed',
    title: '5 Sai lầm phổ biến khi gọi vốn vòng Seed mà Founder cần tránh',
    summary: 'Bài viết chia sẻ từ thực tiễn về những lỗi sai kinh điển khiến Startups bị từ chối ngay từ vòng Seed.',
    content: `Gọi vốn vòng Seed là một cột mốc quan trọng, nhưng rất nhiều Founder mắc phải những lỗi cơ bản. Dưới đây là 5 sai lầm phổ biến:

1. **Định giá quá cao (Overvaluation):** Không ai muốn đầu tư vào một dự án chưa có doanh thu nhưng định giá chục triệu đô.
2. **Thiếu sự rõ ràng trong mô hình kinh doanh:** Nếu bạn không thể giải thích cách kiếm tiền trong 1 câu, nhà đầu tư sẽ bỏ qua.
3. **Quên mất bài toán "Go-to-market":** Có sản phẩm tốt là chưa đủ, bạn cần biết cách bán nó.
4. **Không nắm vững chỉ số tài chính:** Lỗ/lãi, burn rate, runway là những con số phải nằm lòng.
5. **Thiếu sự đồng thuận giữa các Co-founder:** Đội ngũ lục đục là Red Flag lớn nhất.

Hãy chuẩn bị thật kỹ trước khi gõ cửa các quỹ đầu tư!`,
    coverImage: 'https://images.unsplash.com/photo-1553484771-371a605b060b?auto=format&fit=crop&q=80&w=800',
    status: 'PUBLISHED',
    category: 'Funding',
    tags: ['Seed Round', 'Fundraising', 'Startup Guide'],
    author: {
      id: 'u1',
      name: 'Lê Hoàng Nam',
      bio: 'Co-Founder & CTO tại GreenFlow',
      businessId: 'b2',
      businessName: 'GreenFlow',
      followersCount: 1250
    },
    createdAt: SUB_DAYS(3),
    publishedAt: SUB_DAYS(3),
    likesCount: 342,
    bookmarksCount: 45,
    commentsCount: 12,
    viewCount: 1500
  },
  {
    id: 'a2',
    slug: 'xu-huong-fnb-2024',
    title: 'Xu hướng ngành F&B 2024: Chuyển đổi số và Trải nghiệm khách hàng',
    summary: 'Phân tích từ An Nam Culinary về cách công nghệ đang định hình lại ngành nhà hàng tại Việt Nam.',
    content: `Năm 2024 đánh dấu sự chuyển mình mạnh mẽ của ngành F&B. Sau đại dịch, hành vi khách hàng đã thay đổi hoàn toàn.

**1. Đặt món qua App và Kiosk:** 
Tại An Nam Culinary, chúng tôi nhận thấy 40% doanh thu hiện đến từ các nền tảng online. Việc tích hợp hệ thống POS đa kênh là bắt buộc.

**2. Trải nghiệm cá nhân hóa (Hyper-personalization):**
Sử dụng dữ liệu CRM để biết khách hàng thích món gì, dị ứng với gì. Một lời chúc sinh nhật kèm món tráng miệng miễn phí tạo ra khách hàng trung thành.

**3. Tối ưu hóa chuỗi cung ứng bằng AI:**
Dự báo nguyên liệu cần nhập mỗi ngày giúp giảm 15% lượng thức ăn thừa (food waste).

Chuyển đổi số không còn là lựa chọn, nó là vấn đề sống còn của các nhà hàng hiện đại.`,
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
    status: 'PUBLISHED',
    category: 'Growth',
    tags: ['F&B', 'Digital Transformation', 'Trends'],
    author: {
      id: 'u2',
      name: 'Nguyễn Văn An',
      bio: 'Founder & CEO tại An Nam Culinary',
      businessId: 'b1',
      businessName: 'An Nam Culinary',
      followersCount: 840
    },
    createdAt: SUB_DAYS(10),
    publishedAt: SUB_DAYS(9),
    likesCount: 512,
    bookmarksCount: 89,
    commentsCount: 4,
    viewCount: 3200
  }
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'c1',
    articleId: 'a1',
    content: 'Bài viết rất thực tế. Lỗi định giá quá cao là lỗi mình từng mắc phải ở startup đầu tiên.',
    author: {
      id: 'u3',
      name: 'Trần Minh Tuấn',
      bio: 'Serial Entrepreneur'
    },
    createdAt: SUB_DAYS(2),
    replies: [
      {
        id: 'c1-1',
        articleId: 'a1',
        content: 'Chào anh Tuấn, anh có thể chia sẻ thêm về cách anh định giá lại công ty sau đó không ạ?',
        author: {
          id: 'u4',
          name: 'Phạm Thị Lan',
          bio: 'Junior Founder'
        },
        parentId: 'c1',
        createdAt: SUB_DAYS(1)
      }
    ]
  },
  {
    id: 'c2',
    articleId: 'a1',
    content: 'Phần Go-to-market đúng là bài toán khó nhất. Sản phẩm làm ra mà không biết bán cho ai thì cũng vứt.',
    author: {
      id: 'u5',
      name: 'Hoàng Hải',
      bio: 'Marketing Manager'
    },
    createdAt: SUB_DAYS(2)
  }
];
